apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana      
  template:
    metadata:
      labels:
        app: grafana
        grafana: "1"
    spec:
      containers:
      - name: grafana
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: username
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: password
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        nfs:
          path: {{ .Values.global.common.path }}/grafana
          server: {{ .Values.global.common.nfs_server }}
