{{- $current := lookup "v1" "Secret" .Release.Namespace "grafana" -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana
data:
  username: {{ b64enc "admin" }}
  password: {{if $current}} {{ index $current.data "password" }} {{else}} {{b64enc (randAlphaNum 20)}} {{end}}