apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.global.common.mysql.db_name }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: username        
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        nfs:
          path: {{ .Values.global.common.path }}/mysql
          server: {{ .Values.global.common.nfs_server }}
