apiVersion: v1
kind: Service
metadata:
  name: couchbase
spec:
  selector:
    app: couchbase
  type: NodePort
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30891