apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    name: rest
    nodePort: 30920
  - port: 9300
    name: inter-node
    nodePort: 30930
  selector:
    app: elasticsearch