apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.9.0
        ports:
        - containerPort: 5601
        env:
        - name: SERVER_NAME
          value: kibana.zahtlv.freeddns.org
        - name: ELASTICSEARCH_HOSTS
          value: '["http://elasticsearch:9200"]'
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"        
        volumeMounts:
        - name: kibana-storage
          mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-storage
        nfs:
          path: {{ .Values.global.common.path }}/kibana
          server: {{ .Values.global.common.nfs_server }}

