apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
      - name: couchbase
        image: couchbase:community
        ports:
        - containerPort: 8091
        env:
        # - name: INFLUXD_ENGINE_PATH
        #   value: /data/influxdb        
        volumeMounts:
        - name: couchbase-storage
          mountPath: /opt/couchbase/var/lib/couchbase
      volumes:
      - name: couchbase-storage
        nfs:
          path: {{ .Values.global.common.path }}/couchbase
          server: {{ .Values.global.common.nfs_server }}
