mysql:
  hostname: mysql
  password_secret:
    name: mysql
    username: username
    password: password
  
api:    
  command:    
    - /bin/bash
    - -c
    - 'cd api && uvicorn api:app --host 0.0.0.0 --port  8000 --log-config log.config.yaml --log-level debug'
  name: api    
  image: cr.zahtlv.freeddns.org/python-app
  url: http://api:8000