apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.binance.name  }}-script
data:
  {{ .Values.binance.script  }}: |
{{ .Files.Get .Values.binance.balance_script_path | indent 4 }}
  assest.txt: |
{{ .Files.Get .Values.binance.balance_asset_path | indent 4 }}
