apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.binance.convert.name }}     
  labels:
    app: {{ .Values.binance.convert.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.binance.convert.name }}
  template:
    metadata:
      annotations:
        checksum/python-script: {{ .Files.Get .Values.binance.convert.script_path | sha256sum }}
      labels:
        app: {{ .Values.binance.convert.name }}        
        category: {{ .Values.binance.convert.category }}        
        {{ .Values.binance.convert.category }}: "1"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Values.binance.convert.name }}
          image: {{ .Values.binance.convert.image }}
          command: ["python", '/app/binance/{{ .Values.binance.convert.script}}']
          env:
            - name: SLEEPING_TIME
              value: "60"
            - name: INTERVAL
              value: {{ .Values.binance.convert.interval }}              
            - name: ASSETS_FILE
              value: "/app/binance/readers/assets.txt"
            - name: INFLUX_HOST
              valueFrom:
                configMapKeyRef:
                  name: influxdb
                  key: host                  
            - name: INFLUX_PORT
              valueFrom:
                configMapKeyRef:
                  name: influxdb
                  key: port
            - name: INFLUX_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: username
            - name: INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: password
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: token
            - name: INFLUX_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: influxdb
                  key: database
            - name: INFLUX_ORG
              valueFrom:
                configMapKeyRef:
                  name: influxdb
                  key: org
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.binance.convert.category }}
                  key: api_key
            - name: BINANCE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.binance.convert.category }}
                  key: api_secret
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']                                    
            - name: CATEGORY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['category']                        