apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.binance.category }}
data:  
  api_key: {{ .Files.Get .Values.binance.api_key_path | b64enc }}
  api_secret: {{ .Files.Get .Values.binance.api_secret_path  | b64enc }}
