{{- $current := lookup "v1" "Secret" .Release.Namespace "influxdb" -}}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb
type: Opaque
data:
  username: {{ .Values.influxdb.username | b64enc | quote }}
  password: {{if $current}} {{ index $current.data "password" }} {{else}} {{b64enc (randAlphaNum 20)}} {{end}}
  token: {{if $current}} {{ index $current.data "token" }} {{else}} {{b64enc (randAlphaNum 1)}} {{end}}